#@ load("@ytt:data", "data")
---
apiVersion: lb.tanzu.vmware.com/v1alpha1
kind: KubevipCPConfig
metadata:
  name: #@ data.values.TKR_VERSION
  namespace: #@ data.values.GLOBAL_NAMESPACE
  annotations:
    tkg.tanzu.vmware.com/template-config: "true"
spec:
  loadbalancerIPRanges: ""
  loadbalancerCIDRs: ""
