// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/vmware-tanzu/tanzu-framework/cmd/cli/plugin/airgapped-network/cmd"
)

type ImgPkgClientFake struct {
	ImgpkgCopyImagefromtarStub        func(string, string, string)
	imgpkgCopyImagefromtarMutex       sync.RWMutex
	imgpkgCopyImagefromtarArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	ImgpkgCopytotarStub        func(string, string)
	imgpkgCopytotarMutex       sync.RWMutex
	imgpkgCopytotarArgsForCall []struct {
		arg1 string
		arg2 string
	}
	ImgpkgPullImageStub        func(string, string)
	imgpkgPullImageMutex       sync.RWMutex
	imgpkgPullImageArgsForCall []struct {
		arg1 string
		arg2 string
	}
	ImgpkgTagListImageStub        func(string) []string
	imgpkgTagListImageMutex       sync.RWMutex
	imgpkgTagListImageArgsForCall []struct {
		arg1 string
	}
	imgpkgTagListImageReturns struct {
		result1 []string
	}
	imgpkgTagListImageReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ImgPkgClientFake) ImgpkgCopyImagefromtar(arg1 string, arg2 string, arg3 string) {
	fake.imgpkgCopyImagefromtarMutex.Lock()
	fake.imgpkgCopyImagefromtarArgsForCall = append(fake.imgpkgCopyImagefromtarArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ImgpkgCopyImagefromtarStub
	fake.recordInvocation("ImgpkgCopyImagefromtar", []interface{}{arg1, arg2, arg3})
	fake.imgpkgCopyImagefromtarMutex.Unlock()
	if stub != nil {
		fake.ImgpkgCopyImagefromtarStub(arg1, arg2, arg3)
	}
}

func (fake *ImgPkgClientFake) ImgpkgCopyImagefromtarCallCount() int {
	fake.imgpkgCopyImagefromtarMutex.RLock()
	defer fake.imgpkgCopyImagefromtarMutex.RUnlock()
	return len(fake.imgpkgCopyImagefromtarArgsForCall)
}

func (fake *ImgPkgClientFake) ImgpkgCopyImagefromtarCalls(stub func(string, string, string)) {
	fake.imgpkgCopyImagefromtarMutex.Lock()
	defer fake.imgpkgCopyImagefromtarMutex.Unlock()
	fake.ImgpkgCopyImagefromtarStub = stub
}

func (fake *ImgPkgClientFake) ImgpkgCopyImagefromtarArgsForCall(i int) (string, string, string) {
	fake.imgpkgCopyImagefromtarMutex.RLock()
	defer fake.imgpkgCopyImagefromtarMutex.RUnlock()
	argsForCall := fake.imgpkgCopyImagefromtarArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ImgPkgClientFake) ImgpkgCopytotar(arg1 string, arg2 string) {
	fake.imgpkgCopytotarMutex.Lock()
	fake.imgpkgCopytotarArgsForCall = append(fake.imgpkgCopytotarArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.ImgpkgCopytotarStub
	fake.recordInvocation("ImgpkgCopytotar", []interface{}{arg1, arg2})
	fake.imgpkgCopytotarMutex.Unlock()
	if stub != nil {
		fake.ImgpkgCopytotarStub(arg1, arg2)
	}
}

func (fake *ImgPkgClientFake) ImgpkgCopytotarCallCount() int {
	fake.imgpkgCopytotarMutex.RLock()
	defer fake.imgpkgCopytotarMutex.RUnlock()
	return len(fake.imgpkgCopytotarArgsForCall)
}

func (fake *ImgPkgClientFake) ImgpkgCopytotarCalls(stub func(string, string)) {
	fake.imgpkgCopytotarMutex.Lock()
	defer fake.imgpkgCopytotarMutex.Unlock()
	fake.ImgpkgCopytotarStub = stub
}

func (fake *ImgPkgClientFake) ImgpkgCopytotarArgsForCall(i int) (string, string) {
	fake.imgpkgCopytotarMutex.RLock()
	defer fake.imgpkgCopytotarMutex.RUnlock()
	argsForCall := fake.imgpkgCopytotarArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ImgPkgClientFake) ImgpkgPullImage(arg1 string, arg2 string) {
	fake.imgpkgPullImageMutex.Lock()
	fake.imgpkgPullImageArgsForCall = append(fake.imgpkgPullImageArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.ImgpkgPullImageStub
	fake.recordInvocation("ImgpkgPullImage", []interface{}{arg1, arg2})
	fake.imgpkgPullImageMutex.Unlock()
	if stub != nil {
		fake.ImgpkgPullImageStub(arg1, arg2)
	}
}

func (fake *ImgPkgClientFake) ImgpkgPullImageCallCount() int {
	fake.imgpkgPullImageMutex.RLock()
	defer fake.imgpkgPullImageMutex.RUnlock()
	return len(fake.imgpkgPullImageArgsForCall)
}

func (fake *ImgPkgClientFake) ImgpkgPullImageCalls(stub func(string, string)) {
	fake.imgpkgPullImageMutex.Lock()
	defer fake.imgpkgPullImageMutex.Unlock()
	fake.ImgpkgPullImageStub = stub
}

func (fake *ImgPkgClientFake) ImgpkgPullImageArgsForCall(i int) (string, string) {
	fake.imgpkgPullImageMutex.RLock()
	defer fake.imgpkgPullImageMutex.RUnlock()
	argsForCall := fake.imgpkgPullImageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ImgPkgClientFake) ImgpkgTagListImage(arg1 string) []string {
	fake.imgpkgTagListImageMutex.Lock()
	ret, specificReturn := fake.imgpkgTagListImageReturnsOnCall[len(fake.imgpkgTagListImageArgsForCall)]
	fake.imgpkgTagListImageArgsForCall = append(fake.imgpkgTagListImageArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ImgpkgTagListImageStub
	fakeReturns := fake.imgpkgTagListImageReturns
	fake.recordInvocation("ImgpkgTagListImage", []interface{}{arg1})
	fake.imgpkgTagListImageMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ImgPkgClientFake) ImgpkgTagListImageCallCount() int {
	fake.imgpkgTagListImageMutex.RLock()
	defer fake.imgpkgTagListImageMutex.RUnlock()
	return len(fake.imgpkgTagListImageArgsForCall)
}

func (fake *ImgPkgClientFake) ImgpkgTagListImageCalls(stub func(string) []string) {
	fake.imgpkgTagListImageMutex.Lock()
	defer fake.imgpkgTagListImageMutex.Unlock()
	fake.ImgpkgTagListImageStub = stub
}

func (fake *ImgPkgClientFake) ImgpkgTagListImageArgsForCall(i int) string {
	fake.imgpkgTagListImageMutex.RLock()
	defer fake.imgpkgTagListImageMutex.RUnlock()
	argsForCall := fake.imgpkgTagListImageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ImgPkgClientFake) ImgpkgTagListImageReturns(result1 []string) {
	fake.imgpkgTagListImageMutex.Lock()
	defer fake.imgpkgTagListImageMutex.Unlock()
	fake.ImgpkgTagListImageStub = nil
	fake.imgpkgTagListImageReturns = struct {
		result1 []string
	}{result1}
}

func (fake *ImgPkgClientFake) ImgpkgTagListImageReturnsOnCall(i int, result1 []string) {
	fake.imgpkgTagListImageMutex.Lock()
	defer fake.imgpkgTagListImageMutex.Unlock()
	fake.ImgpkgTagListImageStub = nil
	if fake.imgpkgTagListImageReturnsOnCall == nil {
		fake.imgpkgTagListImageReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.imgpkgTagListImageReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *ImgPkgClientFake) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.imgpkgCopyImagefromtarMutex.RLock()
	defer fake.imgpkgCopyImagefromtarMutex.RUnlock()
	fake.imgpkgCopytotarMutex.RLock()
	defer fake.imgpkgCopytotarMutex.RUnlock()
	fake.imgpkgPullImageMutex.RLock()
	defer fake.imgpkgPullImageMutex.RUnlock()
	fake.imgpkgTagListImageMutex.RLock()
	defer fake.imgpkgTagListImageMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ImgPkgClientFake) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cmd.ImgPkgClient = new(ImgPkgClientFake)
